### ISSUE TITLE
Hash matrix for Github Actions makes excludes impossible

### ISSUE THREAD

**Issue by treydock** [voxpupuli/puppet_metadata#13]
https://github.community/t/improve-matrix-exclusion-feature/16340

I tried on at least one pull request to exclude Ubuntu 20.04 and Puppet5 from the acceptance matrix but I think a current limitation of using a hash to define the matrix is that you can't do excludes as excludes expect all parts of the matrix to be either a string or an array.

**Comment by ekohl** [comment]
I noticed the same thing. It was hard to get a combination of a human readable beaker setfile and an exclude. I started out with going for the human readable version and trying to figure out if I could exclude it. If it doesn't work, I'd be interested in alternatives. Perhaps we can store a translation hash and use that in the name instead?

**Comment by ekohl** [comment]
https://github.com/voxpupuli/puppet_metadata/pull/16 should address this. Please take a look.

**Comment by treydock** [comment]
Looks like that should work based on how the example was setup.

**Comment by ekohl** [comment]
We now have an includes that only includes valid combinations. With that I think this can be closed.
